name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
          - { name: macOS, os: macos-latest, triple: x86_64-apple-darwin }
          - { name: Windows, os: windows-2022, triple: x86_64-pc-windows-msvc }
        rust-version: ["1.58"]
        python-version: ["3.10"]

    name: ${{ matrix.target.name }} / ${{ matrix.version }}
    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt, clippy

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Windows needs gmp.h
        if: matrix.target.triple == 'x86_64-pc-windows-msvc'
        run: python -m pip install gmpy2        

      - name: Install dependencies
        run: |
          cd py
          python -m pip install -r requirements-dev.txt
